# To start all the instances
#
# docker-compose up -d
#
# To stop all instances
#
# docker-compose down
#

version: "3.7"

services:

  appweb:
    image: memoor_appweb:latest
    ports:
      - "7168:7168"

  router:
    image: memoor_router:latesr
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - appweb

  