version: "3.7"

services:

  appweb:
    container_name: appweb
    build:
      context: web
    restart: always
    expose:
      - "7168"
    env_file:
      - app.env
    networks:
      - frontend
      - backend

  router:
    container_name: router
    build:
      context: router
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - appweb
    networks:
      - frontend
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:rw

  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge