# To start all the instances
#
# docker-compose up -d
#
# To stop all instances
#
# docker-compose down
#

version: "3.7"

services:

  appweb:
    build:
      context: web
    restart: always
    ports:
      - "7168:7168"

  router:
    build:
      context: router
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - appweb
