#cloud-config

package_update: true
package_upgrade: true
package_reboot_if_required: true

groups:
  - docker

users:
  - name: leaf
    lock_passwd: true
    shell: /bin/bash
    ssh_authorized_keys:
      - ${init_ssh_public_key}
    groups: docker
    sudo: ALL=(ALL) NOPASSWD:ALL

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
  - unattended-upgrades
  - git
  - make
  - awk

write_files:
- path: /opt/app/mail.txt
  owner: 'leaf:docker'
  permissions: "0644"
  defer: true
  content: |
    From: ${from_email}
    To: ${to_email}
    Subject: Deploy ready

    Deploy finished

runcmd:
  - mkdir -r /opt/app
  - cd /opt/app
  - git clone https://github.com/MemoOR/about-me.git
  - cd about-me
  - echo '${env_txt}' > app_env.txt
  - awk -v RS='"[^"]*"' '{gsub(/ /,"\n"); ORS = RT} 1' app_env.txt > app.env
  - source app.env
  - env > envtest.txt
  - make deploy
  - unset $(grep -v '^#' app.env | sed -E 's/([^=]+)=.*/\1/' | xargs)
  - rm app_env.txt
  - curl --url 'smtps://smtp.gmail.com:465' --ssl-reqd --mail-from '${from_email}' --mail-rcpt '${to_email}' --user '${from_email}:${app_password}' --upload-file /opt/app/mail.txt
  - rm /opt/app/mail.txt
